; -- platformio.ini -- MDFreak V0.1.0 -- changelog atthe end of file -------
[platformio]
  src_dir = Bluetti_ESP32

[env]
  lib_deps =
    ;WiFiManager is included as normal library
    PubSubClient@^2.8.0
    ;https://github.com/me-no-dev/ESPAsyncWebServer/archive/master.zip
    ;me-no-dev/ESPAsyncWebServer
    ;AsyncElegantOTA@^2.2.7
    https://github.com/ayushsharma82/ElegantOTA.git
    ;ayushsharma82/ElegantOTA
    h2zero/NimBLE-Arduino@^1.4.1
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5
    adafruit/Adafruit BusIO @ ^1.14.1
  	bblanchon/ArduinoJson@^6.16.1                 ; PRJ..WIFI,WEBSERVER
    Wire
    ;SPI
  ; Post-build script for additional ESP32 configuration
  extra_scripts = post:scripts/post_esp32.py

[env:esp32dev]
  platform = espressif32@6.0.0
  framework = arduino
  board = esp32dev
;board=az-delivery-devkit-v4
  ; Using the min_spiffs.csv partition table to allocate minimal space for SPIFFS,
  ; leaving more room for the application code. Adjust if more SPIFFS storage is needed.
  board_build.partitions = min_spiffs.csv
  monitor_speed = 115200
  upload_speed=921600
  build_flags=
    ; debug config
      -DDEBUG=1
      -DDEBUGDISP=1
      -DDEBUG_BWIFI=1
    ; network config and wifiManager
      -DESP32=1
      -DWIFI_MANAGER_MD=1 ; own managed version of WiFiManager
      -DLANG_DE=1
      -DRESET_WIFI=0 ; set to 1 to reset wifi config at startup
      -DDEV_IP3=47  ; 47
    ; necessary for lib ElegantOTA
      -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    ; relais config
      ; necessary for lib ElegantOTA
      ;-DRELAISMODE=1
      ;-DRELAIS_PIN=22
      ;-DRELAIS_LOW=0  ; LOW=0 or HIGH=1
      ;-DRELAIS_HIGH=1 ; LOW=0 or HIGH=1
      ;; this flag ensures compatibility with the ESPAsyncWebServer library.
      ;-DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    ; I2C config
      ;-DI2C_SDA=21
      ;-DI2C_SCL=22
    ; display config
      ;-DUSE_DISPLAY=1
      ;-DDISPLAYSSD1306=1
      ;-DDISPLAY_SDA_PORT=21
      ;-DDISPLAY_SCL_PORT=22
      ;-DDISPLAY_RST_PORT=16
    ; Bluetti
      -DAC300_ACTIVE=1
      ;-DAP300_ACTIVE=1
      ;-DANDSFREE_ACTIVHE=1
      -DSIM_BLUETTI=0
      ;-DWM_DEBUG_LEVEL=3

;-- changelog ---------------------------------------------------------------
  ;
  ; MD0.1.2 - 2025-10-28 - add scanning of unknown modbus adresses of AC300
  ; - add static IP config for device login and access point to BWifi.cpp
  ;   -> works only once - but not stored in EEPROM
  ;   move details as define to platformio.ini

  ; MD0.1.1 - 2025-10-28 - add scanning of unknown modbus adresses of AC300
  ; - add fields with names including address - example ADR_0x0BF7_UINT
  ;   files: Device_AC300.h, DeviceType.h, MQTT.cpp, BTooth.cpp
  ;
  ; MD0.1.0 - 2025-01-18 - md - extend functionality for AC300
  ; - add and synchronize enums and fields in Device_AC300.h and DeviceType.h
  ; - extend simulation in BTooth.cpp
  ; - update and add evaluation of 'ENUM_FIELD' and 'DECIMAL_ARRAY'
  ;
  ; MD0.0.2 - 2025-01-13 - simuting Bluetti data for MQTT
  ; - introduce simulation for BT to implement MQTT without Bluetti
  ;   - new define SIM_BLUETTI (-> platform.ini)
  ;     used to block unused BT functions
  ;     and activate simulation function
  ;   - simulation starts in function 'handleBluetooth()' and uses
  ;     new function 'sendSIM_data()' to publish data
  ;     uses standard decoding methods
  ;   - works with 8 items
  ;   - add '#include "MQTT.h"' to Bluetooth.cpp
  ; - set default data for connections
  ; - introduce simulation for BT to implement MQTT without Bluetti
  ;
  ; MD0.0.1 - 2025-01-11 - md - initial version
  ; - new define USE_DISPLAY (-> platform.ini)
  ;   ndef USE_DISPLAY = no display implemented
  ; - change code format to MD format for better readability
  ;--------------------------------------------------------------------------
